# Preparing SDSS DR16 VACs


## Introduction

Working with the SDSS DR16 VAC files in preparation for loading into a database. There are one VAC(s) currently targeted for loading into Data Lab:

1. [DR16Q](https://www.sdss.org/dr16/data_access/value-added-catalogs/?vac_id=the-sloan-digital-sky-survey-quasar-catalogue:-sixteenth-data-release-(dr16q))
2. [ELG_CLASSIFICATION](https://www.sdss.org/dr16/data_access/value-added-catalogs/?vac_id=classification-of-intermediate-redshift-emission-line-galaxies)

All of these are conveniently stored as single FITS tables.  However, varying degrees of preprocessing may be needed.

Other resources:

* [SDSS CAS SQL definition files](https://trac.sdss.org/browser/repo/sdss/sas/trunk/sql)


## Setup

In [1]:
# Standard library
from io import BytesIO
import re
import csv
# matplotlib, etc.
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager, FontProperties
import numpy as np
from astropy.io import fits
from astropy.visualization import astropy_mpl_style
from astropy.io.votable import parse_single_table
from astropy.table import Column, Table
plt.style.use(astropy_mpl_style)
matplotlib.rcParams['figure.figsize'] = (10.0, 10.0)
# Data Lab
from dl import queryClient as qc, storeClient as sc
#
# Global constants.
#
release = 16
sas = 'sdss_dr{0:d}://'.format(release)
sdss_run2d = 26
boss_run2d = 'v5_13_0'
m = re.match(r'v(\d+)_(\d+)_(\d+)', boss_run2d)
N, M, P = m.groups()
boss_run2d_int = (int(N) - 5)*10000 + int(M) * 100 + int(P)
# assert matplotlib.rcParams['figure.figsize'] == (10.0, 10.0)

In [2]:
def inthist(foo, show=False):
    """Create a histogram of integer values.

    Parameters
    ----------
    foo : numpy.ndarray
        An array containing integers.
    show : bool, optional
        If ``True``, create a histogram and return the matplotlib.axes.Axes
        instance.

    Returns
    -------
    inthist : mixed
    """
    xmin = min(foo)
    xmax = max(foo)
    x = np.arange( xmin, xmax+1 )
    n = np.zeros( x.shape, dtype=x.dtype )
    for k in range(len(n)):
        n[k] = np.sum( foo == x[k] )
    if show:
        fig = plt.figure(dpi=100)
        ax = fig.add_subplot(111)
        b = ax.bar(x,n,align='center',width=0.5,color='w')
        ax.set_xlim(xmin-1, xmax+1)
        # ax.set_ylim(0, np.ceil(max(n)/10.0)*10.0)
        ax.set_ylim(0, 10**np.ceil(np.log10(max(n))))
        return ax
    else:
        return (n,x)

In [3]:
def sdss_specobjid(plate, fiber, mjd, run2d, line=None, index=None):
    """Convert SDSS spectrum identifiers into CAS-style specObjID.
    Bits are assigned in specObjID thus:
    ===== ========== =============================================================
    Bits  Name       Comment
    ===== ========== =============================================================
    50-63 Plate ID   14 bits
    38-49 Fiber ID   12 bits
    24-37 MJD        Date plate was observed minus 50000 (14 bits)
    10-23 run2d      Spectroscopic reduction version
    0-9   line/index 0 for use in SpecObj files see below for other uses (10 bits)
    ===== ========== =============================================================
    Parameters
    ----------
    plate, fiber, mjd : :class:`int` or array of int
        Plate, fiber ID, and MJD for a spectrum.  If arrays are
        passed, all must have the same length.  The MJD value must be
        greater than 50000.
    run2d : :class:`int`, :class:`str` or array of int or str
        The run2d value must be an integer or a string of the form 'vN_M_P'.
        If an array is passed, it must have the same length as the other
        inputs listed above.  If the string form is used, the values are
        restricted to :math:`5 \le N \le 6`, :math:`0 \le M \le 99`,
        :math:`0 \le P \le 99`.
    line : :class:`int`, optional
        A line index, only used for defining specObjID for SpecLine files.
        `line` and `index` cannot both be non-zero.
    index : :class:`int`, optional
        An index measure, only used for defining specObjID for SpecLineIndex
        files. `line` and `index` cannot both be non-zero.
    Returns
    -------
    :class:`numpy.ndarray` of :class:`numpy.uint64`
        The specObjIDs of the objects.
    Raises
    ------
    :exc:`ValueError`
        If the sizes of the arrays don't match or if the array values are
        out of bounds.
    Notes
    -----
    * On 32-bit systems, makes sure to explicitly declare all inputs as
      64-bit integers.
    * This function defines the SDSS-III/IV version of specObjID, used for
      SDSS DR8 and subsequent data releases.  It is not compatible with
      SDSS DR7 or earlier.
    * If the string form of `run2d` is used, the bits are assigned by
      the formula :math:`(N - 5) \\times 10000 + M \\times 100 + P`.
    Examples
    --------
    >>> from pydl.pydlutils.sdss import sdss_specobjid
    >>> print(sdss_specobjid(4055,408,55359,'v5_7_0'))
    [4565636362342690816]
    """
    if line is not None and index is not None:
        raise ValueError("line and index inputs cannot both be non-zero!")
    if isinstance(plate, int):
        plate = np.array([plate], dtype=np.uint64)
    if isinstance(fiber, int):
        fiber = np.array([fiber], dtype=np.uint64)
    if isinstance(mjd, int):
        mjd = np.array([mjd], dtype=np.uint64) - 50000
    if isinstance(run2d, str):
        try:
            run2d = np.array([int(run2d)], dtype=np.uint64)
        except ValueError:
            # Try a "vN_M_P" string.
            m = re.match(r'v(\d+)_(\d+)_(\d+)', run2d)
            if m is None:
                raise ValueError("Could not extract integer run2d value!")
            else:
                N, M, P = m.groups()
            run2d = np.array([(int(N) - 5)*10000 + int(M) * 100 + int(P)],
                             dtype=np.uint64)
    elif isinstance(run2d, int):
        run2d = np.array([run2d], dtype=np.uint64)
    if line is None:
        line = np.zeros(plate.shape, dtype=plate.dtype)
    else:
        if isinstance(line, int):
            line = np.array([line], dtype=np.uint64)
    if index is None:
        index = np.zeros(plate.shape, dtype=plate.dtype)
    else:
        if isinstance(index, int):
            index = np.array([index], dtype=np.uint64)
    #
    # Check that all inputs have the same shape.
    #
    if plate.shape != fiber.shape:
        raise ValueError("fiber.shape does not match plate.shape!")
    if plate.shape != mjd.shape:
        raise ValueError("mjd.shape does not match plate.shape!")
    if plate.shape != run2d.shape:
        raise ValueError("run2d.shape does not match plate.shape!")
    if plate.shape != line.shape:
        raise ValueError("line.shape does not match plate.shape!")
    if plate.shape != index.shape:
        raise ValueError("index.shape does not match plate.shape!")
    #
    # Check ranges of parameters
    #
    if ((plate < 0) | (plate >= 2**14)).any():
        raise ValueError("plate values are out-of-bounds!")
    if ((fiber < 0) | (fiber >= 2**12)).any():
        raise ValueError("fiber values are out-of-bounds!")
    if ((mjd < 0) | (mjd >= 2**14)).any():
        raise ValueError("MJD values are out-of-bounds!")
    if ((run2d < 0) | (run2d >= 2**14)).any():
        raise ValueError("MJD values are out-of-bounds!")
    if ((line < 0) | (line >= 2**10)).any():
        raise ValueError("line values are out-of-bounds!")
    if ((index < 0) | (index >= 2**10)).any():
        raise ValueError("index values are out-of-bounds!")
    #
    # Compute the specObjID
    #
    specObjID = ((plate << 50) |
                 (fiber << 38) |
                 (mjd << 24) |
                 (run2d << 10) |
                 (line | index))
    return specObjID

In [4]:
def unwrap_specobjid(specObjID, run2d_integer=False, specLineIndex=False):
    """Unwrap CAS-style specObjID into plate, fiber, mjd, run2d.
    See :func:`~pydl.pydlutils.sdss.sdss_specobjid` for details on how the
    bits within a specObjID are assigned.
    Parameters
    ----------
    specObjID : :class:`numpy.ndarray`
        An array containing 64-bit integers or strings.  If strings are passed,
        they will be converted to integers internally.
    run2d_integer : :class:`bool`, optional
        If ``True``, do *not* attempt to convert the encoded run2d values
        to a string.
    specLineIndex : :class:`bool`, optional
        If ``True`` interpret any low-order bits as being an 'index'
        rather than a 'line'.
    Returns
    -------
    :class:`numpy.recarray`
        A record array with the same length as `specObjID`, with the columns
        'plate', 'fiber', 'mjd', 'run2d', 'line'.
    Examples
    --------
    >>> from numpy import array, uint64
    >>> from pydl.pydlutils.sdss import unwrap_specobjid
    >>> unwrap_specobjid(array([4565636362342690816], dtype=uint64))
    rec.array([(4055, 408, 55359, 'v5_7_0', 0)],
              dtype=[('plate', '<i4'), ('fiber', '<i4'), ('mjd', '<i4'), ('run2d', '<U8'), ('line', '<i4')])
    """
    if (specObjID.dtype.type is np.string_ or
        specObjID.dtype.type is np.unicode_):
        tempobjid = specObjID.astype(np.uint64)
    elif specObjID.dtype.type is np.uint64:
        tempobjid = specObjID.copy()
    else:
        raise ValueError('Unrecognized type for specObjID!')
    run2d_dtype = 'U8'
    if run2d_integer:
        run2d_dtype = 'i4'
    line = 'line'
    if specLineIndex:
        line = 'index'
    unwrap = np.recarray(specObjID.shape,
                         dtype=[('plate', 'i4'), ('fiber', 'i4'),
                                ('mjd', 'i4'), ('run2d', run2d_dtype),
                                (line, 'i4')])
    unwrap.plate = np.bitwise_and(tempobjid >> 50, 2**14 - 1)
    unwrap.fiber = np.bitwise_and(tempobjid >> 38, 2**12 - 1)
    unwrap.mjd = np.bitwise_and(tempobjid >> 24, 2**14 - 1) + 50000
    run2d = np.bitwise_and(tempobjid >> 10, 2**14 - 1)
    if run2d_integer:
        unwrap.run2d = run2d
    else:
        N = ((run2d // 10000) + 5).tolist()
        M = ((run2d % 10000) // 100).tolist()
        P = (run2d % 100).tolist()
        unwrap.run2d = np.array(['v{0:d}_{1:d}_{2:d}'.format(n, m, p)
                                 for n, m, p in zip(N, M, P)])
        for r in (26, 103, 104):
            if (run2d == r).any():
                unwrap.run2d[run2d == r] = str(r)
    unwrap[line] = np.bitwise_and(tempobjid, 2**10 - 1)
    return unwrap

## DR16Q

### Overview

* [data model](https://data.sdss.org/datamodel/files/BOSS_QSO/DR16Q/DR16Q_v4.html)
* [data model (superset)](https://data.sdss.org/datamodel/files/BOSS_QSO/DR16Q/DR16Q_Superset_v3.html)
* [Lyke et al. (2020)](https://ui.adsabs.harvard.edu/abs/2020ApJS..250....8L/abstract)

### Preprocessing Plan

* Compute `specObjID`; add `run2d` column.
* Delete photometric information.
* Move duplicate information to separate table.
* Coerce some matching flags to integer.
* Coerce floating point values (except `RA`, `DEC`) to 32-bit float.

### Known Problems

* The columns `GALEX_MATCHED`, `UKIDSS_MATCHED` are stored as float when they should be integers.  The also contain NaN values, and `GALEX_MATCHED` contains some values which are 2.  None of these cases are described in the DR14Q paper.  Only `FIRST_MATCHED` has valid values and is consistent with its description in the paper.
* The photometric id values, `RUN_NUMBER`, `COL_NUMBER`, are all nonsense values.  All identically zero in fact.
* The duplicate column contains extraneous zeroes, and not all duplicates are actually stored in the column.  See below for examples.  It would be much better if the duplicates were a separate table, mapping primary specObjID to duplicate specObjID.
* `TUNIT` columns should be blank when the value has no unit, instead of `-`.
* I would recommend checking that all units in the table conform to the FITS standard.  For example 'Vega' is a description of a unit, not a physical unit. Also, the `RASS_COUNTS` column has units counts/s, which is misleading, because the units are actually log(counts/s).  Exception: nanomaggies are not standard, but are OK.
* Column names, *e.g.* `FLUX_0.2_2.0keV` contain characters that could be interpreted as integers.
* Not all "primary" objects in DR14Q correspond to real objects in the specObjAll table.  And not all "duplicates" correspond to real objects either.  In these cases there are spectra that exist on disk, but are not now, and probably never will be added to CAS.  This makes it particularly difficult to cleanly join DR14Q to specObjAll.

In [5]:
qso_version = 'v4'
vopath = f"{sas}eboss/qso/DR{release:d}Q/DR{release:d}Q_{qso_version}.fits"
with BytesIO(sc.get(vopath, mode='binary')) as q:
    with fits.open(q) as hdulist:
        dr16q = hdulist['CATALOG'].data
qso_superset_version = 'v3'
vopath_superset = f"{sas}eboss/qso/DR{release:d}Q/DR{release:d}Q_superset_{qso_superset_version}.fits"
with BytesIO(sc.get(vopath_superset, mode='binary')) as q:
    with fits.open(q) as hdulist:
        dr16q_superset = hdulist['CATALOG'].data

### specObjID

Compute `specObjID` for the spectra.  Be careful, because there are some SEGUE spectra in the mix!  Also `dr16q_superset` contains objects that were targeted but never observed, so they have no valid `specobjid` value.

In [6]:
run2d = np.array([boss_run2d]*len(dr16q))
run2d_lookup = dict()
for p in np.unique(dr16q['PLATE']):
    q = f"SELECT plateid, plate, mjd, run2d FROM sdss_dr{release:d}.platex WHERE plate = {p:d}"
    response = qc.query(sql=q, fmt='csv', timeout=600)
    ww = dr16q['PLATE'] == p
    r = response.split('\n')[1].split(',')[-1]
    run2d[ww] = r
    run2d_lookup[int(p)] = r

In [7]:
run2d_superset = np.array([boss_run2d]*len(dr16q_superset))
run2d_superset_lookup = dict()
for p in np.unique(dr16q_superset['PLATE']):
    q = f"SELECT plateid, plate, mjd, run2d FROM sdss_dr{release:d}.platex WHERE plate = {p:d}"
    response = qc.query(sql=q, fmt='csv', timeout=600)
    ww = dr16q_superset['PLATE'] == p
    r = response.split('\n')[1].split(',')[-1]
    run2d_superset[ww] = r
    run2d_superset_lookup[int(p)] = r

In [23]:
# specobjid = np.zeros(dr16q.shape, dtype=np.uint64)
w = run2d != boss_run2d
irun2d = np.zeros(dr16q.shape, dtype=np.uint64)
irun2d[w] = [int(x) for x in run2d[w]]
w = run2d == boss_run2d
irun2d[w] = boss_run2d_int
specobjid = sdss_specobjid(dr16q['PLATE'].astype(np.uint64),
                           dr16q['FIBERID'].astype(np.uint64),
                           dr16q['MJD'].astype(np.uint64) - 50000,
                           irun2d)

In [24]:
w = run2d_superset != boss_run2d
irun2d_superset = np.zeros(dr16q_superset.shape, dtype=np.uint64)
irun2d_superset[w] = [int(x) for x in run2d_superset[w]]
w = run2d_superset == boss_run2d
irun2d_superset[w] = boss_run2d_int
specobjid_superset = sdss_specobjid(dr16q_superset['PLATE'].astype(np.uint64),
                                    dr16q_superset['FIBERID'].astype(np.uint64),
                                    dr16q_superset['MJD'].astype(np.uint64) - 50000,
                                    irun2d_superset)

### Photometric information

These columns contain no useful information at all, so drop them.  Get information by joining on `specobj` instead.

In [26]:
objid = np.zeros(len(dr16q), dtype=np.uint64)
w = dr16q['OBJID'] != ''
objid[w] = np.array(list(map(int, dr16q['OBJID'][w].tolist())), dtype=np.uint64)

In [27]:
w = dr16q['SKYVERSION'] != 2
dr16q['SKYVERSION'][w], dr16q['OBJID'][w], dr16q['RERUN_NUMBER'][w], dr16q['RUN_NUMBER'][w], dr16q['CAMCOL_NUMBER'][w], dr16q['FIELD_NUMBER'][w], dr16q['ID_NUMBER'][w]
# assert (dr16q['RERUN_NUMBER'] == '-').all()
# assert (dr16q['COL_NUMBER'] == 0).all()
# assert (dr16q['FIELD_NUMBER'] == 0).all()
# assert (dr16q['OBJ_ID'] == '-').all()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [28]:
w = (dr16q['OBJID'] == '') & (dr16q['SKYVERSION'] != 0)
dr16q['SKYVERSION'][w], dr16q['OBJID'][w], dr16q['RERUN_NUMBER'][w], dr16q['RUN_NUMBER'][w], dr16q['CAMCOL_NUMBER'][w], dr16q['FIELD_NUMBER'][w], dr16q['ID_NUMBER'][w]

(array([2, 2], dtype=uint8),
 chararray(['', ''], dtype='<U19'),
 chararray(['301', '301'], dtype='<U3'),
 array([1729, 4836], dtype=int32),
 array([5, 5], dtype=int32),
 array([365, 251], dtype=int32),
 array([105,  25], dtype=int32))

### Targeting flags

Make sure these don't require any special `np.uint64` handling.

In [25]:
assert (dr16q['BOSS_TARGET1'] < 9223372036854775808).all()
assert (dr16q['ANCILLARY_TARGET1'] < 9223372036854775808).all()
assert (dr16q['ANCILLARY_TARGET2'] < 9223372036854775808).all()
assert (dr16q['EBOSS_TARGET0'] < 9223372036854775808).all()
assert (dr16q['EBOSS_TARGET1'] < 9223372036854775808).all()
assert (dr16q['EBOSS_TARGET2'] < 9223372036854775808).all()

### Duplicates

Move the duplicate information to a separate table. Some duplicates are disk only; they do not exist in the `specobjall` table.  We will load all duplicates unflagged, then use a database query to flag the duplicates that do not exist in the database.

In [30]:
dr16q['NSPEC'].max()

73

In [29]:
dr16q_superset['NSPEC'].max()

73

In [ ]:
matplotlib.rcParams['figure.figsize'] = (10, 10)
n, x = inthist(dr16q['NSPEC'])
w = n > 0
fig = plt.figure(dpi=100)
ax = fig.add_subplot(1, 1, 1)
b = ax.bar(x[w], n[w], align='center', width=0.5, color='k')
foo = ax.set_yscale('log')
foo = ax.set_xlim(dr16q['NSPEC'].min()-1, dr16q['NSPEC'].max()+1)
# foo = ax.set_ylim(0, np.ceil(np.log10(max(n))))
foo = ax.set_title(f'Number of DR{release:d}Q Duplicates [{qso_version}]')
foo = ax.set_xlabel('Number of Duplicates [NSPEC]')
foo = ax.set_ylabel('N')

In [ ]:
w = dr16q['NSPEC'] == 73
dr16q['PLATE_DUPLICATE'][w, :]

In [25]:
with open('dr16q_duplicates.csv', 'w', newline='') as csvfile:
    dw = csv.writer(csvfile)
    dw.writerow(['specobjid', 'dupspecobjid', 'run2d', 'plate', 'mjd', 'fiberid', 'disk_only'])
    for k in range(len(dr16q)):
        if dr16q[k]['NSPEC'] > 0:
            w = dr16q['PLATE_DUPLICATE'][k, :] > 0
            Nd = w.sum()
            irun2d = np.zeros((Nd,), dtype=np.uint64)
            plates = dr16q['PLATE_DUPLICATE'][k, w]
            mjds = dr16q['MJD_DUPLICATE'][k, w]
            fibers = dr16q['FIBERID_DUPLICATE'][k, w]
            for i, p in enumerate(plates):
                try:
                    foo = run2d_lookup[p]
                except KeyError:
                    q = f"SELECT run2d FROM sdss_dr{release}.platex WHERE plate = {p:d} AND mjd = {mjds[i]:d}"
                    try:
                        vot = qc.query(sql=q, fmt='votable', timeout=600)
                    except qc.queryClientError as e:
                        if str(e) == 'Error: SQL query did not return any records':
                            q = f"SELECT run2d FROM sdss_dr{release:d}.platex WHERE plate = {p:d}"
                            vot = qc.query(sql=q, fmt='votable', timeout=600)
                        else:
                            raise
                    result = parse_single_table(BytesIO(vot.encode('utf-8')))
                    foo = run2d_lookup[p] = result.array['run2d'][0]
                if foo == boss_run2d:
                    irun2d[i] = boss_run2d_int
                else:
                    irun2d[i] = int(foo)
            dupspecobjid = sdss_specobjid(plates.astype(np.uint64),
                                          fibers.astype(np.uint64),
                                          mjds.astype(np.uint64) - 50000,
                                          irun2d)
            for l in range(Nd):
                dw.writerow([specobjid[k].astype(np.int64),
                             dupspecobjid[l].astype(np.int64),
                             run2d_lookup[plates[l]],
                             plates[l],
                             mjds[l],
                             fibers[l],
                             'FALSE'])

In [26]:
with open('dr16q_superset_duplicates.csv', 'w', newline='') as csvfile:
    dw = csv.writer(csvfile)
    dw.writerow(['specobjid', 'dupspecobjid', 'run2d', 'plate', 'mjd', 'fiberid', 'disk_only'])
    for k in range(len(dr16q_superset)):
        if dr16q_superset[k]['NSPEC'] > 0:
            w = dr16q_superset['PLATE_DUPLICATE'][k, :] > 0
            Nd = w.sum()
            irun2d = np.zeros((Nd,), dtype=np.uint64)
            plates = dr16q_superset['PLATE_DUPLICATE'][k, w]
            mjds = dr16q_superset['MJD_DUPLICATE'][k, w]
            fibers = dr16q_superset['FIBERID_DUPLICATE'][k, w]
            for i, p in enumerate(plates):
                try:
                    foo = run2d_superset_lookup[p]
                except KeyError:
                    q = f"SELECT run2d FROM sdss_dr{release}.platex WHERE plate = {p:d} AND mjd = {mjds[i]:d}"
                    try:
                        vot = qc.query(sql=q, fmt='votable', timeout=600)
                    except qc.queryClientError as e:
                        if str(e) == 'Error: SQL query did not return any records':
                            q = f"SELECT run2d FROM sdss_dr{release:d}.platex WHERE plate = {p:d}"
                            vot = qc.query(sql=q, fmt='votable', timeout=600)
                        else:
                            raise
                    result = parse_single_table(BytesIO(vot.encode('utf-8')))
                    foo = run2d_superset_lookup[p] = result.array['run2d'][0]
                if foo == boss_run2d:
                    irun2d[i] = boss_run2d_int
                else:
                    irun2d[i] = int(foo)
            dupspecobjid = sdss_specobjid(plates.astype(np.uint64),
                                          fibers.astype(np.uint64),
                                          mjds.astype(np.uint64) - 50000,
                                          irun2d)
            for l in range(Nd):
                dw.writerow([specobjid_superset[k].astype(np.int64),
                             dupspecobjid[l].astype(np.int64),
                             run2d_superset_lookup[plates[l]],
                             plates[l],
                             mjds[l],
                             fibers[l],
                             'FALSE'])

In [27]:
4857325810397499392 in specobjid_superset

True

In [28]:
unwrap_specobjid(np.array([4857325810397499392], dtype=np.uint64))

rec.array([(4314, 704, 55855, 'v5_13_0', 0)],
          dtype=[('plate', '<i4'), ('fiber', '<i4'), ('mjd', '<i4'), ('run2d', '<U8'), ('line', '<i4')])

In [ ]:
t = Table(dr16q)
for c in dr16q.columns.names:
    if dr16q[c].dtype.type is np.float64 and c != 'RA' and c != 'DEC':
        # print(c)
        t[c] = dr16q[c].astype(np.float32)
w = dr16q['OBJID'] == ''
t['OBJID'][w] = '0'
t.remove_columns(['PLATE_DUPLICATE', 'MJD_DUPLICATE', 'FIBERID_DUPLICATE', 'SPECTRO_DUPLICATE',
                  'SKYVERSION', 'RUN_NUMBER', 'RERUN_NUMBER', 'CAMCOL_NUMBER', 'FIELD_NUMBER', 'ID_NUMBER'])
t.add_column(Column(name='SPECOBJID', data=np.array(list(map(str, specobjid.tolist())))), index=0)
t.add_column(Column(name='RUN2D', data=run2d), index=4)
t.add_column(Column(name='DISK_ONLY', data=np.zeros((len(dr16q),), dtype=bool)))

In [34]:
ts = Table(dr16q_superset)
for c in dr16q_superset.columns.names:
    if dr16q_superset[c].dtype.type is np.float64 and c != 'RA' and c != 'DEC':
        # print(c)
        ts[c] = dr16q_superset[c].astype(np.float32)
w = dr16q_superset['OBJID'] == ''
ts['OBJID'][w] = '0'
ts.remove_columns(['PLATE_DUPLICATE', 'MJD_DUPLICATE', 'FIBERID_DUPLICATE', 'SPECTRO_DUPLICATE',
                   'SKYVERSION', 'RUN_NUMBER', 'RERUN_NUMBER', 'CAMCOL_NUMBER', 'FIELD_NUMBER', 'ID_NUMBER'])
ts.add_column(Column(name='SPECOBJID', data=np.array(list(map(str, specobjid_superset.tolist())))), index=0)
ts.add_column(Column(name='RUN2D', data=run2d_superset), index=4)
ts.add_column(Column(name='DISK_ONLY', data=np.zeros((len(dr16q_superset),), dtype=bool)))

In [ ]:
t

In [35]:
ts

<Table length=1440615>
     SPECOBJID           SDSS_NAME      ... SN_MEDIAN_ALL DISK_ONLY
       str20               str18        ...    float32       bool  
-------------------- ------------------ ... ------------- ---------
12699048555652075520 000000.04+064602.3 ...      8.410045     False
 9840548378089639936 000000.04+064602.3 ...     10.498864     False
 8663957691486720000 000000.05+272811.6 ...      4.093675     False
 8838397398546141184 000000.06-021415.2 ...     1.9698929     False
 8725944871075205120 000000.15+353104.2 ...     24.468967     False
 7330979594269642752 000000.18+282535.8 ...     7.2176948     False
 7330777284130131968 000000.22+275753.3 ...      8.988609     False
 8046850724964093952 000000.29-073054.8 ...     2.8898847     False
 8724779932985872384 000000.33+310325.3 ...     2.2885926     False
12699294021622976512 000000.36+070350.8 ...      1.420663     False
                 ...                ... ...           ...       ...
 8663951644172767232 235959.76+281402.9 ...     1.7132785     False
 8664958796840587264 235959.78+285717.0 ...       2.03567     False
 7330985091827781632 235959.78+285717.0 ...      2.025133     False
 8032282195761844224 235959.78+285717.0 ...      2.139166     False
 7330763815112691712 235959.80+274621.3 ...      8.075862     False
 8044620915265523712 235959.83+344315.0 ...      6.060774     False
12697902038996242432 235959.90+031606.9 ...     12.908586     False
 9841507702370750464 235959.90+031606.9 ...     14.484946     False
 8551281102568050688 235959.94+204315.8 ...     5.3310122     False
 8044626962579476480 235959.98+344449.6 ...      4.994688     False

In [ ]:
t.write('dr16q_datalab.fits')

In [36]:
ts.write('dr16q_superset_datalab.fits')

## ELG_CLASSIFICATION

In [5]:
elg_version = 'v1_0'
vopath = f"{sas}eboss/elg/elg_classifier/{elg_version}/eboss-elg-classification_{elg_version}.fits"
with BytesIO(sc.get(vopath, mode='binary')) as q:
    with fits.open(q) as hdulist:
        elg = hdulist[1].data

In [6]:
t = Table(elg)
t['MJD'] = t['MJD'].astype(np.int32)
t['PLATE'] = t['PLATE'].astype(np.int16)
t['FIBERID'] = t['FIBERID'].astype(np.int16)
t['TYPE'] = t['TYPE'].astype(np.int16)
m = re.match(r'v(\d+)_(\d+)_(\d+)', boss_run2d)
N, M, P = m.groups()
br = (int(N) - 5)*10000 + int(M) * 100 + int(P)
specobjid = sdss_specobjid(t['PLATE'].astype(np.uint64), t['FIBERID'].astype(np.uint64), t['MJD'].astype(np.uint64) - 50000, np.array([br]*len(t), dtype=np.uint64)).astype(np.int64)

In [7]:
for i in range(len(t)):
    q = f"SELECT run2d, plate, mjd, fiberid FROM sdss_dr{release:d}.specobjall WHERE specobjid = {specobjid[i]:d}"
    # print(q)
    # print(t['PLATE'][i], t['MJD'][i], t['FIBERID'][i])
    result = qc.query(sql=q, fmt='csv', timeout=600)
    # print(result)
    run2d, plate, mjd, fiberid = result.split('\n')[1].strip().split(',')
    assert run2d == 'v5_13_0'
    assert int(plate) == t['PLATE'][i]
    assert int(mjd) == t['MJD'][i]
    assert int(fiberid) == t['FIBERID'][i]

In [8]:
(np.unique(specobjid) == specobjid).all()

False

In [11]:
sorted(np.unique(specobjid)) == sorted(specobjid)

True

In [12]:
t.add_column(specobjid, name='SPECOBJID', index=0)

In [13]:
t

<Table length=49270>
     SPECOBJID        MJD  PLATE ...         i_z          TYPE
       int64         int32 int16 ...       float64       int16
-------------------- ----- ----- ... ------------------- -----
 4303371506141122560 55544  3822 ... 0.39862390589964036     2
 5821040883685150720 56063  5170 ...  0.5378095733832176     3
 7292484314855657472 56365  6477 ... 0.15757234002977327     2
 6816383680770232320 56089  6054 ...  0.4669580317397113     3
 4533082846131408896 55325  4026 ...  0.4009193508476123     3
 5130795513344708608 55588  4557 ...  0.3446281437224066     2
-8499255819306250240 57427  8835 ...  0.2531994720201034     3
 5130800461147033600 55588  4557 ... 0.29393535702795504     2
 5130800736024940544 55588  4557 ... 0.23993540184093476     2
 5821055177336311808 56063  5170 ... 0.32001098407217654     2
                 ...   ...   ... ...                 ...   ...
 8533334049095438336 56954  7579 ...  0.1298090611654068     1
 5821021367353757696 56063  5170 ... 0.25257767507837414     1
 6416549023826857984 55953  5699 ...  0.2278627677751821     3
 6816369387119071232 56089  6054 ...  0.4576615331346723     2
 6816370761508605952 56089  6054 ...  0.3169029970651067     2
 6816372685653954560 56089  6054 ... 0.48611159766346645     2
 4303366833216704512 55544  3822 ...  0.3972637199276434     4
 6816377908334186496 56089  6054 ... 0.42177113231123897     2
 6816378183212093440 56089  6054 ... 0.41591716607513973     3
 5130790015786569728 55588  4557 ...  0.4415182763793055     2

In [14]:
t.write('elg_classification_datalab.fits')